// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WorlflowOptimizationModelsLibrary.Context;

namespace WorlflowOptimizationModelsLibrary.Migrations
{
    [DbContext(typeof(WorkflowOpimizationDBContext))]
    [Migration("20190525092005_UpdateMaterialTypeDB")]
    partial class UpdateMaterialTypeDB
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WorlflowOptimizationModelsLibrary.Models.BuildingObject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("BuildingObjects");
                });

            modelBuilder.Entity("WorlflowOptimizationModelsLibrary.Models.Material", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("BuildingObjectId");

                    b.Property<int>("MaterialTypeId");

                    b.Property<int>("Quantity")
                        .HasMaxLength(10);

                    b.Property<int?>("WorkingDayId");

                    b.HasKey("Id");

                    b.HasIndex("BuildingObjectId");

                    b.HasIndex("MaterialTypeId");

                    b.HasIndex("WorkingDayId");

                    b.ToTable("Materials");
                });

            modelBuilder.Entity("WorlflowOptimizationModelsLibrary.Models.MaterialType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("MaterialType");
                });

            modelBuilder.Entity("WorlflowOptimizationModelsLibrary.Models.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("BuildingObjectId");

                    b.Property<int>("Quantity")
                        .HasMaxLength(10);

                    b.Property<int>("ServiceTypeId");

                    b.Property<int?>("WorkingDayId");

                    b.HasKey("Id");

                    b.HasIndex("BuildingObjectId");

                    b.HasIndex("ServiceTypeId");

                    b.HasIndex("WorkingDayId");

                    b.ToTable("Services");
                });

            modelBuilder.Entity("WorlflowOptimizationModelsLibrary.Models.ServiceType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("ServiceType");
                });

            modelBuilder.Entity("WorlflowOptimizationModelsLibrary.Models.Worker", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<int>("WorkingDayId");

                    b.HasKey("Id");

                    b.HasIndex("WorkingDayId");

                    b.ToTable("Workers");
                });

            modelBuilder.Entity("WorlflowOptimizationModelsLibrary.Models.WorkingDay", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Date");

                    b.HasKey("Id");

                    b.ToTable("WorkingDays");
                });

            modelBuilder.Entity("WorlflowOptimizationModelsLibrary.Models.Material", b =>
                {
                    b.HasOne("WorlflowOptimizationModelsLibrary.Models.BuildingObject", "BuildingObject")
                        .WithMany("Materials")
                        .HasForeignKey("BuildingObjectId");

                    b.HasOne("WorlflowOptimizationModelsLibrary.Models.MaterialType", "MaterialType")
                        .WithMany("Materials")
                        .HasForeignKey("MaterialTypeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("WorlflowOptimizationModelsLibrary.Models.WorkingDay", "WorkingDay")
                        .WithMany("Materials")
                        .HasForeignKey("WorkingDayId");
                });

            modelBuilder.Entity("WorlflowOptimizationModelsLibrary.Models.Service", b =>
                {
                    b.HasOne("WorlflowOptimizationModelsLibrary.Models.BuildingObject", "BuildingObject")
                        .WithMany("Services")
                        .HasForeignKey("BuildingObjectId");

                    b.HasOne("WorlflowOptimizationModelsLibrary.Models.ServiceType", "ServiceTypes")
                        .WithMany("Services")
                        .HasForeignKey("ServiceTypeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("WorlflowOptimizationModelsLibrary.Models.WorkingDay", "WorkingDay")
                        .WithMany("Services")
                        .HasForeignKey("WorkingDayId");
                });

            modelBuilder.Entity("WorlflowOptimizationModelsLibrary.Models.Worker", b =>
                {
                    b.HasOne("WorlflowOptimizationModelsLibrary.Models.WorkingDay", "WorkingDay")
                        .WithMany("Workers")
                        .HasForeignKey("WorkingDayId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
